# -*- coding: utf-8 -*-
"""C-108

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zbZ6ow4xRIcgKTKnSfgpFpFTU7KTXtNy
"""

from google.colab import files
file_to_upload=files.upload()

import random
import plotly.figure_factory as ff

result=[]
for i in range(0,100):
  dice1=random.randint(1,6)
  dice2=random.randint(1,6)
  sum=dice1+dice2
  result.append(sum)

figure=ff.create_distplot([result],["sums"], show_hist=False)
figure.show()

import pandas as pd

df=pd.read_csv("data3.csv")
print(df)

heightList=df["Height(Inches)"].to_list()
print(heightList)

height=ff.create_distplot([heightList],["height"], show_hist=False)
height.show()

weightList=df["Weight(Pounds)"].to_list()
print(weightList)

weight=ff.create_distplot([weightList],["weight"],show_hist=False)
weight.show()



